### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ArnautDaniel** [lutherannn/py-blackjack#1]
Maybe the language should be changed to C?

**Comment by lutherannn** [comment]
you're done

**Comment by ArnautDaniel** [comment]
>Make the program not run if emacs is installed on a machine

Don't think I can implement this as I'll be writing in, well, Emacs...

**Comment by lutherannn** [comment]
>Don't think I can implement this as I'll be writing in, well, Emacs...

well then it should be easy, if it doesn't run then it works. don't even have to install emacs
